# Generated by Django 2.2.6 on 2019-11-02 16:31

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('postal_code', localflavor.us.models.USPostalCodeField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
    ]
