# Generated by Django 2.2.7 on 2019-11-16 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_change_postalcode_to_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='us_state',
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
